### ISSUE TITLE
kind elastic 7.5.1 chart - access denied

### ISSUE THREAD

**Issue by jerishsd** [elastic/helm-charts#429] opened 2020-01-04 16:36 UTC
Summary:
Elastic chart mounts gives an error within kubernetes in docker (kind) - Repro and logs below
Guess the latest docs indicate that the following examples are not good beyond 6.8.6 ?
https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/kubernetes-kind

Tried checking out helm-charts, adapting values.yaml with the extraInitContainers etc.,
no breakthrough.

Found a similar issue and tried all options there as well,
https://github.com/elastic/helm-charts/issues/258

Help appreciated :)

Repro:
```
helm install my-release-elasticsearch elastic/elasticsearch --set imageTag=7.5.1
```

Error:
```
kubectl logs elasticsearch-master-0

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"type": "server", "timestamp": "2020-01-04T16:19:48,108Z", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "uncaught exception in thread [main]", 
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.5.1.jar:7.5.1]",
"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.5.1.jar:7.5.1]",
"Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
"at org.elasticsearch.node.Node.<init>(Node.java:607) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]",
"... 6 more",
"Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",
"at java.nio.file.Files.createDirectory(Files.java:693) ~[?:?]",
"at java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[?:?]",
"at java.nio.file.Files.createDirectories(Files.java:786) ~[?:?]",
"at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:272) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:209) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:269) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.node.Node.<init>(Node.java:273) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.node.Node.<init>(Node.java:253) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.5.1.jar:7.5.1]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]",
"... 6 more"] }
```

**Comment by jmlrt** [comment] 2020-01-06 14:04
Hi @jerishsd,
Thank you for submitting this issue.

I guess `VolumeMounts` is missing in your `extraInitContainer`.

Could you try using the same config that is used for [kind](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/kubernetes-kind/values.yaml#L23-L35):

```
extraInitContainers: |
  - name: create
    image: busybox:1.28
    command: ['mkdir', '/usr/share/elasticsearch/data/nodes/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-master
  - name: file-permissions
    image: busybox:1.28
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-master
```

**Comment by jerishsd** [comment] 2020-01-07 05:43
Thanks @jmlrt for the response.
Tried the following and getting a template error.

git clone https://github.com/elastic/helm-charts.git
cp ./helm-charts/elasticsearch/examples/kubernetes-kind/values.yaml ./helm-charts/elasticsearch/

helm install my-release-elastic ./helm-charts/elasticsearch/  --set imageTag=7.5.1
Error: template: elasticsearch/templates/statefulset.yaml:15:24: executing "elasticsearch/templates/statefulset.yaml" at <include "elasticsearch.esMajorVersion" .>: error calling include: template: elasticsearch/templates/_helpers.tpl:59:78: executing "elasticsearch.esMajorVersion" at <.Values.image>: wrong type for value; expected string; got interface {}

**Comment by jmlrt** [comment] 2020-01-07 07:50
Of course this is not working as by doing that you are removing all default values of the charts.

[kind value file](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/kubernetes-kind/values.yaml) should be used to override default values with `helm install [CHART] --file valueFiles` not replace them.

**Comment by jerishsd** [comment] 2020-01-07 17:45
@jmlrt Thanks much for the response, tried both options below, still containers error out/crash loopback.
Guess I'm still doing a rookie mistake somewhere :)

helm install my-release-elastic ./helm-charts/elasticsearch/  --values ./helm-charts/elasticsearch/examples/kubernetes-kind/values.yaml

helm install my-release-elastic ./helm-charts/elasticsearch/  --values ./helm-charts/elasticsearch/values.yaml ./helm-charts/elasticsearch/examples/kubernetes-kind/values.yaml

kubectl get pods --all-namespaces
NAMESPACE     NAME                                               READY   STATUS                  RESTARTS   AGE
default       elasticsearch-master-0                             0/1     Init:Error              5          3m5s
default       elasticsearch-master-1                             0/1     Init:Error              5          3m5s
default       elasticsearch-master-2                             0/1     Init:CrashLoopBackOff   4          3m4s
kube-system   coredns-5c98db65d4-ddgmv                           1/1     Running                 0          12h
kube-system   coredns-5c98db65d4-zjt8t                           1/1     Running                 0          12h
kube-system   etcd-devcluster-control-plane                      1/1     Running                 0          12h
kube-system   kindnet-kw96j                                      1/1     Running                 0          12h
kube-system   kube-apiserver-devcluster-control-plane            1/1     Running                 0          12h
kube-system   kube-controller-manager-devcluster-control-plane   1/1     Running                 0          12h
kube-system   kube-proxy-nshtg                                   1/1     Running                 0          12h
kube-system   kube-scheduler-devcluster-control-plane            1/1     Running                 0          12h



kubectl logs elasticsearch-master-0
Error from server (BadRequest): container "elasticsearch" in pod "elasticsearch-master-0" is waiting to start: PodInitializing

**Comment by pbecotte** [comment] 2020-01-07 23:11
Do you have a default storage class in your cluster? can you run ANY stateful sets? How was your cluster deployed? If you get `waiting to start` errors, you chould do `kubectl describe...` to see what the issue is.

**Comment by jerishsd** [comment] 2020-01-08 05:14
@pbecotte 
I create the kind cluster very basic with just, kind create cluster --name="devcluster"
Should I add more options !?

This is the only chart that's offending, eg.. the charts below go fine..

helm install my-release-kong stable/kong --version 0.28.0
helm install my-release-mongo stable/mongodb --version 7.6.2 --set persistence.mountPath=../../installs/data
helm install my-release-fusionauth ../../installs/third-party/fusionauth-containers/helm/fusionauth/

**Comment by jmlrt** [comment] 2020-01-08 09:42
OK, I took some time to setup kind and reproduce your issue.

Following https://github.com/elastic/helm-charts/issues/388#issuecomment-569330365, this is related to https://github.com/kubernetes-sigs/kind/issues/830.

This should be fixed in kind next release (https://github.com/kubernetes-sigs/kind/pull/1157 to fix it was merged one month ago).

Meanwhile, the workaround is to install manually [Rancher Local Path Provisioner](https://github.com/rancher/local-path-provisioner) and use `local-path`storage class for Elasticsearch volumes.

```
# Install local-path storage class
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

# Fix specific helm values for kind
cat << EOF > ./helm-charts/elasticsearch/examples/kubernetes-kind/values.yaml
antiAffinity: "soft"
esJavaOpts: "-Xmx128m -Xms128m"
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 100M
EOF

# Deploy helm chart
helm install my-release-elastic ./helm-charts/elasticsearch/ --values ./helm-charts/elasticsearch/examples/kubernetes-kind/values.yaml
```

I'll create a PR to update the kind example with this workaround.

**Closed** 2020-01-08 10:47 UTC
Labels: bug

**Comment by jerishsd** [comment] 2020-01-08 13:15
Thx much @jmlrt 🙏
