### ISSUE TITLE
[logstash] error validating data: ValidationError(StatefulSet.spec)

### ISSUE THREAD

**Issue by StefanSa** [elastic/helm-charts#620] opened 2020-05-14 10:40 UTC
**Chart version:**
7.70 pre-release

**Kubernetes version:**
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
local

**Helm Version:**
v3.2.0

**Describe the bug:**
get with `helm install logstash elastic/logstash --set imageTag=7.7.0 (7.6.2 also)`

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec`

**Comment by jmlrt** [comment] 2020-05-14 12:23
Hi @StefanSa as mentionned in the README, Elastic Helm charts aren't supporting Helm v3 yet.
Closing it as duplicate of #497

**Closed by jmlrt** 2020-05-14 12:23 UTC
Labels: duplicate
