### ISSUE TITLE
metricbeat-7.4.1 metrics pod in CrashLoopBackOff status

### ISSUE THREAD

**Issue by msdemt** [elastic/helm-charts#379] opened 2019-11-20 02:36 UTC
**Chart version:**
metricbeat-7.4.1
**Kubernetes version:**
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
bare metal
**Helm Version:**
helm v3

**Describe the bug:**

metrics pod in CrashLoopBackOff status

**Steps to reproduce:**

1. backup metricbeat/values.yaml file

```shell
wget https://github.com/elastic/helm-charts/archive/7.4.1.tar.gz
tar -zxf 7.4.1.tar.gz
cd helm-charts-7.4.1
cp metricbeat/values.yaml metricbeat/values.yaml.orig
```

2. modify metricbeat/values.yaml

```shell
[root@k8s-m1 helm-charts-7.4.1]# diff metricbeat/values.yaml metricbeat/values.yaml.orig
86c86
< hostPathRoot: /home/data/metricbeat
---
> hostPathRoot: /var/lib
```

3. deploy metricbeat

```shell
[root@k8s-m1 helm-charts-7.4.1]# helm dependency update metricbeat/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "pingcap" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading kube-state-metrics from repo http://mirror.azure.cn/kubernetes/charts/
Deleting outdated charts
[root@k8s-m1 helm-charts-7.4.1]# helm install ./metricbeat/ --namespace logging --name-template metricbeat
```

then the metrisc pod in CrashLoopBackOff status

```
[root@k8s-m1 metricbeat]# helm list -n logging
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
elasticsearch	logging  	1       	2019-11-19 18:42:21.758092111 +0800 CST	deployed	elasticsearch-7.4.1	7.4.1      
filebeat     	logging  	1       	2019-11-19 19:07:38.211114723 +0800 CST	deployed	filebeat-7.4.1     	7.4.1      
kibana       	logging  	1       	2019-11-19 19:01:10.634913603 +0800 CST	deployed	kibana-7.4.1       	7.4.1      
metricbeat   	logging  	1       	2019-11-20 09:59:07.497691483 +0800 CST	deployed	metricbeat-7.4.1   	7.4.1
[root@k8s-m1 metricbeat]# kubectl get pods -n logging  
NAME                                             READY   STATUS             RESTARTS   AGE
elasticsearch-master-0                           1/1     Running            0          15h
elasticsearch-master-1                           1/1     Running            0          15h
elasticsearch-master-2                           1/1     Running            0          15h
filebeat-filebeat-4trbf                          1/1     Running            0          15h
filebeat-filebeat-cnn4n                          1/1     Running            0          15h
filebeat-filebeat-gx5vj                          1/1     Running            0          15h
filebeat-filebeat-h57xx                          1/1     Running            0          15h
filebeat-filebeat-xk6w8                          1/1     Running            0          15h
kibana-kibana-7b9c744857-mbn5w                   1/1     Running            0          15h
metricbeat-kube-state-metrics-5698984f89-k446t   1/1     Running            0          30m
metricbeat-metricbeat-czsh5                      1/1     Running            0          30m
metricbeat-metricbeat-kg7f4                      1/1     Running            0          30m
metricbeat-metricbeat-metrics-5d49889f4-j892t    0/1     CrashLoopBackOff   10         30m
metricbeat-metricbeat-sxnjm                      1/1     Running            0          30m
metricbeat-metricbeat-tvs46                      1/1     Running            0          30m
metricbeat-metricbeat-wnrjn                      1/1     Running            0          30m
[root@k8s-m1 metricbeat]# kubectl logs -n logging -f metricbeat-metricbeat-metrics-5d49889f4-j892t 
2019-11-20T02:25:54.034Z	INFO	instance/beat.go:607	Home path: [/usr/share/metricbeat] Config path: [/usr/share/metricbeat] Data path: [/usr/share/metricbeat/data] Logs path: [/usr/share/metricbeat/logs]
2019-11-20T02:25:54.035Z	INFO	instance/beat.go:615	Beat ID: 66f93d6f-9335-46bc-8063-0a2f1db3a671
2019-11-20T02:25:54.093Z	INFO	[seccomp]	seccomp/seccomp.go:124	Syscall filter successfully installed
2019-11-20T02:25:54.093Z	INFO	[beat]	instance/beat.go:903	Beat info	{"system_info": {"beat": {"path": {"config": "/usr/share/metricbeat", "data": "/usr/share/metricbeat/data", "home": "/usr/share/metricbeat", "logs": "/usr/share/metricbeat/logs"}, "type": "metricbeat", "uuid": "66f93d6f-9335-46bc-8063-0a2f1db3a671"}}}
2019-11-20T02:25:54.093Z	INFO	[beat]	instance/beat.go:912	Build info	{"system_info": {"build": {"commit": "12ee6cd05c1bfdc69721ddab1f473417b1514576", "libbeat": "7.4.1", "time": "2019-10-22T16:26:05.000Z", "version": "7.4.1"}}}
2019-11-20T02:25:54.093Z	INFO	[beat]	instance/beat.go:915	Go runtime info	{"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":32,"version":"go1.12.9"}}}
2019-11-20T02:25:54.095Z	INFO	[beat]	instance/beat.go:919	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2019-10-08T00:01:09Z","containerized":true,"name":"metricbeat-metricbeat-metrics-5d49889f4-j892t","ip":["127.0.0.1/8","172.30.182.53/32"],"kernel_version":"5.0.1-1.el7.elrepo.x86_64","mac":["82:7c:62:52:74:98"],"os":{"family":"redhat","platform":"centos","name":"CentOS Linux","version":"7 (Core)","major":7,"minor":6,"patch":1810,"codename":"Core"},"timezone":"UTC","timezone_offset_sec":0}}}
2019-11-20T02:25:54.095Z	INFO	[beat]	instance/beat.go:948	Process info	{"system_info": {"process": {"capabilities": {"inheritable":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"permitted":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"effective":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"bounding":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"ambient":null}, "cwd": "/usr/share/metricbeat", "exe": "/usr/share/metricbeat/metricbeat", "name": "metricbeat", "pid": 1, "ppid": 0, "seccomp": {"mode":"filter","no_new_privs":true}, "start_time": "2019-11-20T02:25:53.750Z"}}}
2019-11-20T02:25:54.096Z	INFO	instance/beat.go:292	Setup Beat: metricbeat; Version: 7.4.1
2019-11-20T02:25:54.096Z	INFO	[index-management]	idxmgmt/std.go:178	Set output.elasticsearch.index to 'metricbeat-7.4.1' as ILM is enabled.
2019-11-20T02:25:54.096Z	INFO	elasticsearch/client.go:170	Elasticsearch url: http://elasticsearch-master:9200
2019-11-20T02:25:54.096Z	INFO	[publisher]	pipeline/module.go:97	Beat name: metricbeat-metricbeat-metrics-5d49889f4-j892t
2019-11-20T02:25:54.107Z	INFO	instance/beat.go:422	metricbeat start running.
2019-11-20T02:25:54.107Z	WARN	[cfgwarn]	api/server.go:34	EXPERIMENTAL: Metrics endpoint is enabled.
2019-11-20T02:25:54.107Z	INFO	api/server.go:38	Starting stats endpoint
2019-11-20T02:25:54.108Z	INFO	api/server.go:49	Metrics endpoint listening on: localhost:5066
2019-11-20T02:25:54.107Z	INFO	[monitoring]	log/log.go:118	Starting metrics logging every 30s
2019-11-20T02:26:00.297Z	INFO	pipeline/output.go:95	Connecting to backoff(elasticsearch(http://elasticsearch-master:9200))
2019-11-20T02:26:00.303Z	INFO	elasticsearch/client.go:743	Attempting to connect to Elasticsearch version 7.4.1
2019-11-20T02:26:00.539Z	INFO	[index-management]	idxmgmt/std.go:252	Auto ILM enable success.
2019-11-20T02:26:00.540Z	INFO	[index-management.ilm]	ilm/std.go:134	do not generate ilm policy: exists=true, overwrite=false
2019-11-20T02:26:00.540Z	INFO	[index-management]	idxmgmt/std.go:265	ILM policy successfully loaded.
2019-11-20T02:26:00.540Z	INFO	[index-management]	idxmgmt/std.go:394	Set setup.template.name to '{metricbeat-7.4.1 {now/d}-000001}' as ILM is enabled.
2019-11-20T02:26:00.540Z	INFO	[index-management]	idxmgmt/std.go:399	Set setup.template.pattern to 'metricbeat-7.4.1-*' as ILM is enabled.
2019-11-20T02:26:00.540Z	INFO	[index-management]	idxmgmt/std.go:433	Set settings.index.lifecycle.rollover_alias in template to {metricbeat-7.4.1 {now/d}-000001} as ILM is enabled.
2019-11-20T02:26:00.540Z	INFO	[index-management]	idxmgmt/std.go:437	Set settings.index.lifecycle.name in template to {metricbeat-7.4.1 {"policy":{"phases":{"hot":{"actions":{"rollover":{"max_age":"30d","max_size":"50gb"}}}}}}} as ILM is enabled.
2019-11-20T02:26:00.566Z	INFO	template/load.go:88	Template metricbeat-7.4.1 already exists and will not be overwritten.
2019-11-20T02:26:00.566Z	INFO	[index-management]	idxmgmt/std.go:289	Loaded index template.
2019-11-20T02:26:00.567Z	INFO	[index-management]	idxmgmt/std.go:300	Write alias successfully generated.
2019-11-20T02:26:00.568Z	INFO	pipeline/output.go:105	Connection to backoff(elasticsearch(http://elasticsearch-master:9200)) established
E1120 02:26:03.619247       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 268 [running]:
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3fbb0e0, 0x6eebab0)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x3fbb0e0, 0x6eebab0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/elastic/beats/libbeat/common/kubernetes.(*MetaGeneratorConfig).ResourceMetadata(0xc000361d60, 0x4a54f80, 0xc001d6b8c0, 0x451844f)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/metadata.go:113 +0x485
github.com/elastic/beats/metricbeat/module/kubernetes/util.NewResourceMetadataEnricher.func1(0xc0009cb650, 0x4a54f80, 0xc001d6b8c0)
	/go/src/github.com/elastic/beats/metricbeat/module/kubernetes/util/kubernetes.go:149 +0x1e9
github.com/elastic/beats/metricbeat/module/kubernetes/util.buildMetadataEnricher.func1(0x44e89a0, 0xc001d6b8c0)
	/go/src/github.com/elastic/beats/metricbeat/module/kubernetes/util/kubernetes.go:268 +0xb1
github.com/elastic/beats/libbeat/common/kubernetes.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/eventhandler.go:54
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).process.func1(0xc000223c00, 0x3d87fe0, 0xc00094c600, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:284 +0x1e0
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).process(0xc000223c00, 0x4a92400, 0xc0009e4000, 0x1)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:292 +0x4d
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).Start.func1()
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:247 +0x48
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0013d2130)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0013d2130, 0x3b9aca00, 0x0, 0x1, 0xc0018ba780)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0013d2130, 0x3b9aca00, 0xc0018ba780)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).Start
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:246 +0x1ef
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c21015]

goroutine 268 [running]:
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x3fbb0e0, 0x6eebab0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/elastic/beats/libbeat/common/kubernetes.(*MetaGeneratorConfig).ResourceMetadata(0xc000361d60, 0x4a54f80, 0xc001d6b8c0, 0x451844f)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/metadata.go:113 +0x485
github.com/elastic/beats/metricbeat/module/kubernetes/util.NewResourceMetadataEnricher.func1(0xc0009cb650, 0x4a54f80, 0xc001d6b8c0)
	/go/src/github.com/elastic/beats/metricbeat/module/kubernetes/util/kubernetes.go:149 +0x1e9
github.com/elastic/beats/metricbeat/module/kubernetes/util.buildMetadataEnricher.func1(0x44e89a0, 0xc001d6b8c0)
	/go/src/github.com/elastic/beats/metricbeat/module/kubernetes/util/kubernetes.go:268 +0xb1
github.com/elastic/beats/libbeat/common/kubernetes.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/eventhandler.go:54
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).process.func1(0xc000223c00, 0x3d87fe0, 0xc00094c600, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:284 +0x1e0
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).process(0xc000223c00, 0x4a92400, 0xc0009e4000, 0x1)
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:292 +0x4d
github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).Start.func1()
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:247 +0x48
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0013d2130)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0013d2130, 0x3b9aca00, 0x0, 0x1, 0xc0018ba780)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0013d2130, 0x3b9aca00, 0xc0018ba780)
	/go/src/github.com/elastic/beats/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/elastic/beats/libbeat/common/kubernetes.(*watcher).Start
	/go/src/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go:246 +0x1ef
```

But when I deploy metricbeat-7.3.2，it seems OK

```
[root@k8s-m1 helm-charts]# helm list -n logging
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
elasticsearch	logging  	1       	2019-11-19 18:42:21.758092111 +0800 CST	deployed	elasticsearch-7.4.1	7.4.1      
filebeat     	logging  	1       	2019-11-19 19:07:38.211114723 +0800 CST	deployed	filebeat-7.4.1     	7.4.1      
kibana       	logging  	1       	2019-11-19 19:01:10.634913603 +0800 CST	deployed	kibana-7.4.1       	7.4.1      
metricbeat   	logging  	1       	2019-11-20 10:34:14.11389979 +0800 CST 	deployed	metricbeat-7.3.2   	7.3.2
[root@k8s-m1 helm-charts]# kubectl get pods -n logging 
NAME                                             READY   STATUS    RESTARTS   AGE
elasticsearch-master-0                           1/1     Running   0          15h
elasticsearch-master-1                           1/1     Running   0          15h
elasticsearch-master-2                           1/1     Running   0          15h
filebeat-filebeat-4trbf                          1/1     Running   0          15h
filebeat-filebeat-cnn4n                          1/1     Running   0          15h
filebeat-filebeat-gx5vj                          1/1     Running   0          15h
filebeat-filebeat-h57xx                          1/1     Running   0          15h
filebeat-filebeat-xk6w8                          1/1     Running   0          15h
kibana-kibana-7b9c744857-mbn5w                   1/1     Running   0          15h
metricbeat-kube-state-metrics-5698984f89-4qxgx   1/1     Running   0          55s
metricbeat-metricbeat-f5trd                      1/1     Running   0          55s
metricbeat-metricbeat-f7wnt                      1/1     Running   0          55s
metricbeat-metricbeat-fdz2g                      1/1     Running   0          55s
metricbeat-metricbeat-metrics-66fc965b9-lr6wf    1/1     Running   0          55s
metricbeat-metricbeat-pcg2h                      1/1     Running   0          55s
metricbeat-metricbeat-rtk8v                      1/1     Running   0          55s
```

**Expected behavior:**
expect the metric pod in running state

**Comment by fatmcgav** [comment] 2019-11-20 08:18
@msdemt Thank you for opening an issue. 

From looking at the details you've supplied, and the assertion that the same config works on `7.3.2`, but _doesn't_ work on `7.4.1`, this _sounds_ like a bug in Metricbeat to me... 

I had a quick search through the issues on the [elastic/beats](https://github.com/elastic/beats) repo and found this one - https://github.com/elastic/beats/issues/14320

It looks like this bug has been fixed, and will be included in the upcoming `7.5` release of the stack, which is due within the next week or two.

I'm going to go ahead and close this issue out, as the problem is with metricbeat rather than the helm chart. 
However please feel free to ask any more questions etc :)

**Closed by fatmcgav** 2019-11-20 08:18 UTC
