### ISSUE TITLE
cluster autodiscover wrong when customizing nodeGroup

### ISSUE THREAD

**Issue by ArgTang** [elastic/helm-charts#227] opened 2019-07-18 08:02 UTC
**Chart version:** 7.2.0

**Describe the bug:**
When creating a cluster and using custom nodeGroup, 

**Steps to reproduce:**

1. deploy chart with custom nodeGroup value ex mygroup
2. cluster autodiscover is looking for `elasticsearch-master-headless`
3. cluster wont discover other nodes and wont become green

**Expected behavior:**
cluster autodiscover is looking for `elasticsearch-mygroup-headless`

**Any additional context:**

_helpers.tpl
```yaml
{{- define "uname" -}}
{{ .Values.clusterName }}-{{ .Values.nodeGroup }} # this is correct
{{- end -}}

{{- define "masterService" -}}
{{- if empty .Values.masterService -}}
{{ .Values.clusterName }}-master # hardcoded bug here
{{- else -}}
{{ .Values.masterService }} # could this change to tpl?
{{- end -}}
{{- end -}}
```

**Comment by congcongke** [comment] 2019-07-18 08:14
I hit the same issue!

**Comment by Crazybus** [comment] 2019-07-18 14:33
If you are changing the default `nodeGroup` for your group of masters then you also need to set `masterService`. In your case it will need to be `elasticsearch-mygroup-headless`. This exists to make it possible to build clusters using multiple releases with different node types. 

It's documented in the readme here: 

> masterService | Optional. The service name used to connect to the masters. You only need to set this if your master nodeGroup is set to something other than master. See Clustering and Node Discovery for more information.

And also a bit more in-depth about why in the [clustering and node discovery section](https://github.com/elastic/helm-charts/tree/master/elasticsearch#clustering-and-node-discovery)

**Comment by Crazybus** [comment] 2019-07-18 14:34
> I hit the same issue! But I set the masterService to cluster.name-nodeGroup.

@congcongke Could you give me the output of `helm get elasticsearch` (replace `elasticsearch` with your helm release name).

**Comment by Crazybus** [comment] 2019-07-18 14:36
One potential way to improve this experience for someone not using the default `master` group for their masters would be to see if `roles.master: true` is set, and in that case to always set the `masterService` to `{{ .Values.clusterName }}-{{ .Values.nodeGroup }}`. However it could potentially break things if someone has a use case where they have multiple node groups that are all master eligible.

**Comment by congcongke** [comment] 2019-07-19 08:18
> > I hit the same issue! But I set the masterService to cluster.name-nodeGroup.
> 
> @congcongke Could you give me the output of `helm get elasticsearch` (replace `elasticsearch` with your helm release name).
clusterName: test
nodeGroup: audit

masterService: test-audit

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
  storageClass: ceph

antiAffinity: soft

**Comment by Crazybus** [comment] 2019-07-19 14:27
@congcongke What you are doing looks correct, and those values work for me when I deploy a cluster. Can you give me the output of `helm get sts elasticsearch-master -o yaml` instead then? I want to be sure that the values are being merged properly. 

> I just have my own yaml to overwrite the exist with helm install --values test.yaml

Can you also give me the exact commands that you are running to deploy this? That command is invalid because it is missing the chart name to be installed. It was probably an example...however explaining exactly how you are deploying it will help me to troubleshoot this.

**Comment by congcongke** [comment] 2019-07-22 06:26
> Can you also give me the exact commands that you are running to deploy this? That command is invalid because it is missing the chart name to be installed. It was probably an example...however explaining exactly how you are deploying it will help me to troubleshoot this.

Sorry for the misunderstanding. In my previous expression, the issue is solved wit `masterService=clusterName-nodeGroup`.
Actually at the beginning I encounter the same problem as this issue described, but then I found that the masterService should be set correctly to fix it.

Sorry again!!

`
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: qce-audit-data
  labels:
    heritage: "Tiller"
    release: "audittest"
    chart: "elasticsearch-7.2.0"
    app: "qce-audit-data"
spec:
  serviceName: qce-audit-data-headless
  selector:
    matchLabels:
      app: "qce-audit-data"
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: qce-audit-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClass: ceph

  template:
    metadata:
      name: "qce-audit-data"
      labels:
        heritage: "Tiller"
        release: "audittest"
        chart: "elasticsearch-7.2.0"
        app: "qce-audit-data"
      annotations:

    spec:
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "qce-audit-data"
      terminationGracePeriodSeconds: 120
      volumes:
      initContainers:
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        image: "reg.kpaas.io/kpaas/elasticsearch:7.2.0"
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        resources:
          {}

      containers:
      - name: "elasticsearch"
        image: "reg.kpaas.io/kpaas/elasticsearch:7.2.0"
        imagePullPolicy: "IfNotPresent"
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5

          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                # If the node is starting up wait for the cluster to be ready (request params: 'wait_for_status=green&timeout=1s' )
                # Once it has started only check that the node itself is responding
                START_FILE=/tmp/.es_start_file

                http () {
                    local path="${1}"
                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                      BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                    else
                      BASIC_AUTH=''
                    fi
                    curl -XGET -s -k --fail ${BASIC_AUTH} http://127.0.0.1:9200${path}
                }

                if [ -f "${START_FILE}" ]; then
                    echo 'Elasticsearch is already running, lets check the node is healthy'
                    http "/"
                else
                    echo 'Waiting for elasticsearch cluster to become cluster to be ready (request params: "wait_for_status=green&timeout=1s" )'
                    if http "/_cluster/health?wait_for_status=green&timeout=1s" ; then
                        touch ${START_FILE}
                        exit 0
                    else
                        echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
                        exit 1
                    fi
                fi
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 2Gi

        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: "qce-audit-data-0,qce-audit-data-1,qce-audit-data-2,"
          - name: discovery.seed_hosts
            value: "qce-audit-data-headless"
          - name: cluster.name
            value: "qce"
          - name: network.host
            value: "0.0.0.0"
          - name: ES_JAVA_OPTS
            value: "-Xmx1g -Xms1g"
          - name: node.data
            value: "true"
          - name: node.ingest
            value: "true"
          - name: node.master
            value: "true"
        volumeMounts:
          - name: "qce-audit-data"
            mountPath: /usr/share/elasticsearch/data
`

**Comment by Crazybus** [comment] 2019-07-22 13:58
> Sorry again!!

No worries! Glad that you got it working and thank you for following up :)

**Closed** 2019-10-11 08:28 UTC
Labels: bug
