### ISSUE TITLE
Logstash can't start on k8s 1.16.6

### ISSUE THREAD

**Issue by PabloDeCortes** [elastic/helm-charts#562] opened 2020-04-05 17:23 UTC
**Chart version:**
stable/latest

**Kubernetes version:**
1.16.6

**Kubernetes provider:**
DigitalOcean

**Helm Version:**
v3.1.2

**Describe the bug:**
When you try to run `helm install` there is an issue `Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec`

**Steps to reproduce:**
Run `helm install logstash elastic/logstash --namespace elastic`

**Expected behavior:**
Helm release successfully deployed to k8s

**Comment by jmlrt** [comment] 2020-04-06 14:45
Duplicate of https://github.com/elastic/helm-charts/issues/497

**Closed by jmlrt** 2020-04-06 14:45 UTC
Labels: bug, duplicate, helm3
