### ISSUE TITLE
Logstash install failed on k8s

### ISSUE THREAD

**Issue by debjitk** [elastic/helm-charts#609] opened 2020-05-09 19:32 UTC
Logstash install failed on k8s with the following message

`unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec`

**Comment by jmlrt** [comment] 2020-05-11 09:39
Duplicate of #497

**Closed by jmlrt** 2020-05-11 09:39 UTC
Labels: duplicate
