### ISSUE TITLE
[elasticsearch] Make master sidecar container optional

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/helm-charts#191] opened 2019-06-28 14:41 UTC
**Describe the feature:**

is master sidecar container needed for all versions? as I understand it should have been fixed as mentioned in https://github.com/elastic/helm-charts/issues/63#issuecomment-472339526, maybe it makes sense to introduce additional value and add this container optionally?

I've tried to reproduce the issue as described here https://github.com/elastic/helm-charts/issues/63
For version `7.2.0` I can't reproduce 
```
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
``` 
and during the re-election API call 
```$ watch -n1 time curl -s http://localhost:9200/_cat/master?v``` 
doesn't hang.

**Comment by Crazybus** [comment] 2019-07-01 08:03
> is master sidecar container needed for all versions? as I understand it should have been fixed as mentioned in #63 (comment)

If it really has been fixed in #63 then we can disable it by default. 

> maybe it makes sense to introduce additional value and add this container optionally?

Yup!

> and during the re-election API call
> $ watch -n1 time curl -s http://localhost:9200/_cat/master?v
> doesn't hang.

Were you able to reproduce the problem with this test on versions before 7.2? If I recall correctly the issue with using `_cat/master` is that it doesn't have a timeout and only returns once the new master has been elected. The best way to reproduce it (and to test if it is fixed) seems to be doing lots of writes while the currently active master is being shut down. 

I'm going to do some testing with 7.2.0 to see if it is indeed fixed or not. If so then we can disable this workaround!

**Comment by Crazybus** [comment] 2019-07-01 08:39
Yup it's fixed for good! I'll disable it by default and add a value to re-enable it for Elasticsearch < 7.2.0.

**Closed** 2019-07-01 09:48 UTC

**Comment by tetianakravchenko** [comment] 2019-07-01 15:58
@Crazybus thank you! It was really fast 👍
