### ISSUE TITLE
[logstash] upload chart to repository so it can be used

### ISSUE THREAD

**Issue by travisghansen** [elastic/helm-charts#365] opened 2019-11-12 21:21 UTC
I'd like to start working with the `logstash` chart but it seems it hasn't been uploaded yet. Thanks!

```
helm up
...

helm search elastic/
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                  
elastic/elasticsearch   7.4.1           7.4.1           Official Elastic helm chart for Elasticsearch
elastic/filebeat        7.4.1           7.4.1           Official Elastic helm chart for Filebeat     
elastic/kibana          7.4.1           7.4.1           Official Elastic helm chart for Kibana       
elastic/metricbeat      7.4.1           7.4.1           Official Elastic helm chart for Metricbeat   
```

**Comment by jmlrt** [comment] 2019-11-13 07:39
@travisghansen, I'm sorry Logstash hasn't been released to our Helm repository yet, see more details in #333 (comment)).

Meanwhile I've updated the doc in #364 to provide instruction to use the chart from master branch.

Closing the issue as duplicate of #353.

**Closed by jmlrt** 2019-11-13 07:39 UTC
Labels: duplicate
